#!/usr/bin/env node
// Step 2 of pr-self-review: deterministic checks (no LLM) → <run>/hard.json.
//
//   node hard-checks.mjs --run <dir> [--no-commands]
//
// Rules are documented in references/hard-checks.md — keep the two in sync.
import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import path from 'node:path';
import { parseArgs, readFileOrNull, readJson, tryGit, writeJson } from './lib.mjs';

const args = parseArgs(process.argv.slice(2));
if (typeof args.run !== 'string') {
  console.error('usage: hard-checks.mjs --run <dir> [--no-commands]');
  process.exit(2);
}
const collect = readJson(path.join(args.run, 'collect.json'));
const { root, mergeBase } = collect;
const files = collect.files;
const findings = [];
const warnings = [];
const add = (f) => findings.push({ source: 'hard-check', suppressible: true, line: null, ...f });

const changed = (p) => files.some((f) => f.path === p);
const current = (p) => readFileOrNull(path.join(root, p));
const atBase = (p) => tryGit(['show', `${mergeBase}:${p}`], { cwd: root });

// ---- 1. migrations: generated by `pnpm db:generate`, never hand-edited ----
const MIGRATIONS = 'server/src/db/migrations/';
const schemaChanged = files.some((f) => f.path === 'server/src/db/schema.ts' || f.path.startsWith('server/src/db/schema/'));
for (const f of files.filter((f) => f.path.startsWith(MIGRATIONS))) {
  const generatedArtifact = f.path.endsWith('.sql') || f.path.endsWith('_snapshot.json');
  if (!generatedArtifact) continue; // meta/_journal.json is legitimately updated by db:generate
  if (['M', 'D', 'R'].includes(f.status)) {
    add({
      severity: 'critical', rule: 'do-not-touch', file: f.path, suppressible: false,
      message: 'An existing migration was edited/deleted. Migrations are generated, never hand-edited.',
      fix: 'Revert this file; change `server/src/db/schema*` and run `cd server && pnpm db:generate`.',
    });
  } else if (!schemaChanged) {
    add({
      severity: 'critical', rule: 'do-not-touch', file: f.path, suppressible: false,
      message: 'A new migration without any change to `server/src/db/schema*` — looks hand-written.',
      fix: 'Change the schema and generate the migration with `pnpm db:generate`.',
    });
  }
}

// ---- 2. grounding gate + injection guard must not lose call sites ----
for (const token of ['groundFindings(', 'INJECTION_GUARD']) {
  const removed = files.flatMap((f) => f.removed.filter((t) => t.includes(token)).map(() => f.path));
  const added = files.reduce((n, f) => n + f.added.filter((a) => a.text.includes(token)).length, 0);
  if (removed.length > added) {
    add({
      severity: 'critical', rule: 'do-not-touch', file: removed[0], suppressible: false,
      message: `\`${token.replace('(', '')}\` loses ${removed.length - added} occurrence(s) in this diff — the grounding gate / injection guard must never be bypassed or weakened.`,
      fix: 'Restore the removed call/usage.',
    });
  }
}
for (const p of ['reviewer-core/src/grounding.ts', 'reviewer-core/src/prompt.ts']) {
  if (changed(p)) warnings.push({ rule: 'guard-file-touched', message: `\`${p}\` changed — reviewers must confirm the grounding gate / INJECTION_GUARD is not weakened.` });
}

// ---- 3. secrets ----
const SECRET_PATTERNS = [
  ['OpenAI/Anthropic/OpenRouter key', /\bsk-(?:ant-|or-)?[A-Za-z0-9_-]{20,}/],
  ['GitHub token', /\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{30,}|\bgithub_pat_[A-Za-z0-9_]{40,}/],
  ['AWS access key', /\bAKIA[0-9A-Z]{16}\b/],
  ['Slack token', /\bxox[abprs]-[A-Za-z0-9-]{10,}/],
  ['private key', /-----BEGIN [A-Z ]*PRIVATE KEY-----/],
];
const knownSecrets = loadKnownSecrets();
for (const f of files) {
  const base = path.basename(f.path);
  if (f.status !== 'D' && (/^\.env(\..+)?$/.test(base) && !/\.(example|sample|template)$/.test(base) || base === 'secrets.json')) {
    add({
      severity: 'critical', rule: 'secret-leak', file: f.path, suppressible: false,
      message: `\`${base}\` is part of the change — secrets live only in \`~/.devdigest/secrets.json\` or env.`,
      fix: 'Remove the file from the change and add it to `.gitignore`.',
    });
  }
  for (const a of f.added) {
    const hit = SECRET_PATTERNS.find(([, re]) => re.test(a.text));
    const known = knownSecrets.find((s) => a.text.includes(s.value));
    if (hit || known) {
      // Never echo the line: the report must not become a second leak.
      add({
        severity: 'critical', rule: 'secret-leak', file: f.path, line: a.line, suppressible: false,
        message: known ? `Added line contains the value of \`${known.name}\`.` : `Added line looks like a ${hit[0]}.`,
        fix: 'Remove it, rotate the credential if it was ever committed, read it via the secrets adapter.',
      });
    }
  }
}

// ---- 4. the two copies of @devdigest/shared ----
const SHARED = ['server/src/vendor/shared/', 'client/src/vendor/shared/'];
const seenPairs = new Set();
for (const f of files) {
  const side = SHARED.findIndex((p) => f.path.startsWith(p));
  if (side === -1 || f.status === 'D' || !f.path.endsWith('.ts')) continue;
  const rel = f.path.slice(SHARED[side].length);
  if (seenPairs.has(rel)) continue;
  seenPairs.add(rel);
  const [a, b] = SHARED.map((p) => p + rel);
  const [nowA, nowB] = [current(a), current(b)];
  if (nowA === null || nowB === null || nowA === nowB) continue;
  const [baseA, baseB] = [atBase(a), atBase(b)];
  const other = changed(a) ? b : a;
  if (baseA !== null && baseA === baseB) {
    add({
      severity: 'critical', rule: 'broken-contract', file: f.path,
      message: `\`${rel}\` was identical in both copies of @devdigest/shared at base; this change makes them differ.`,
      fix: `Apply the same change to \`${other}\` (or explain in a self-review-ignore why the copies must differ).`,
    });
  } else if (!(changed(a) && changed(b))) {
    add({
      severity: 'major', rule: 'shared-copy-one-side', file: f.path,
      message: `Only one copy of \`${rel}\` changed; \`${other}\` did not (the copies already differed).`,
      fix: `Mirror the change in \`${other}\` or say in the PR why not.`,
    });
  }
}

// ---- 5. reviewer prompts: docs copy vs seed copy ----
const docsPrompts = files.filter((f) => /^docs\/agent-prompts\/.+-reviewer\.md$/.test(f.path));
const seedChanged = changed('server/src/db/seed-prompts.ts');
if (docsPrompts.length && !seedChanged) {
  add({
    severity: 'major', rule: 'prompt-copies', file: docsPrompts[0].path,
    message: 'A reviewer prompt changed in `docs/agent-prompts/` but not in `server/src/db/seed-prompts.ts`.',
    fix: 'Update the seed copy too; the DB row (source of truth at run time) needs a re-seed or manual update.',
  });
} else if (seedChanged && !docsPrompts.length) {
  add({
    severity: 'major', rule: 'prompt-copies', file: 'server/src/db/seed-prompts.ts',
    message: 'Seed reviewer prompts changed but `docs/agent-prompts/*-reviewer.md` did not.',
    fix: 'Mirror the change in docs; the DB row needs a re-seed or manual update.',
  });
}

// ---- 6. branch hygiene (warnings only) ----
if (['main', 'master', 'HEAD'].includes(collect.branch)) {
  warnings.push({ rule: 'branch-main', message: `You are on \`${collect.branch}\`. Create a feature branch: \`git switch -c feat/<name>\`.` });
}
if (collect.dirty) {
  warnings.push({ rule: 'dirty-tree', message: 'Uncommitted changes were reviewed too — this verdict cannot unlock a push. Commit, then re-run `/pr-self-review`.' });
}
if (collect.scope === 'staged') {
  warnings.push({ rule: 'staged-only', message: 'Staged-only review — informational, cannot unlock a push.' });
}
for (const name of collect.unmappedSkills) {
  warnings.push({ rule: 'unmapped-skill', message: `Skill \`${name}\` is not in references/routing.md — add a row or list it under "Never routed".` });
}
warnings.push(...featureMixWarnings());

// ---- 7. typecheck / tests / arch:check of touched packages ----
const commands = [];
let incomplete = false;
if (args['no-commands'] === true) {
  incomplete = true;
  commands.push({ package: '*', command: '—', status: 'skipped', reason: '--no-commands' });
} else {
  const CODE = /\.(ts|tsx|js|mjs|cjs|json)$/;
  const touched = new Set(files.filter((f) => !f.path.startsWith(MIGRATIONS) && CODE.test(f.path)).map((f) => f.package));
  if (touched.has('reviewer-core')) touched.add('server:typecheck'); // server compiles reviewer-core's source
  const plan = [];
  if (touched.has('server')) {
    plan.push(['server', ['pnpm', 'typecheck'], ['server', 'reviewer-core']]);
    plan.push(['server', ['pnpm', 'exec', 'vitest', 'run', '--exclude', '**/*.it.test.ts'], ['server', 'reviewer-core']]);
    plan.push(['server', ['pnpm', 'arch:check'], ['server']]);
  } else if (touched.has('server:typecheck')) {
    plan.push(['server', ['pnpm', 'typecheck'], ['server', 'reviewer-core']]);
  }
  if (touched.has('client')) {
    plan.push(['client', ['pnpm', 'typecheck'], ['client']]);
    plan.push(['client', ['pnpm', 'test'], ['client']]);
  }
  if (touched.has('reviewer-core')) {
    plan.push(['reviewer-core', ['npm', 'run', 'typecheck'], ['reviewer-core']]);
    plan.push(['reviewer-core', ['npm', 'test'], ['reviewer-core']]);
  }
  if (touched.has('e2e')) plan.push(['e2e', ['npm', 'run', 'typecheck'], ['e2e']]);

  for (const [pkg, cmd, needs] of plan) {
    const label = cmd.join(' ');
    const missing = needs.filter((n) => !existsSync(path.join(root, n, 'node_modules')));
    if (missing.length) {
      incomplete = true;
      commands.push({
        package: pkg, command: label, status: 'skipped',
        reason: `deps not installed in ${missing.join(', ')} (pnpm install / npm ci)`,
      });
      continue;
    }
    const started = Date.now();
    const res = spawnSync(cmd[0], cmd.slice(1), {
      cwd: path.join(root, pkg), encoding: 'utf8', timeout: 15 * 60_000,
      env: { ...process.env, CI: '1', FORCE_COLOR: '0' },
    });
    const output = `${res.stdout ?? ''}${res.stderr ?? ''}`;
    const tail = output.trim().split('\n').slice(-40).join('\n');
    if (res.error && res.error.code === 'ENOENT') {
      incomplete = true;
      commands.push({ package: pkg, command: label, status: 'skipped', reason: `\`${cmd[0]}\` not on PATH` });
      continue;
    }
    const ok = res.status === 0;
    commands.push({ package: pkg, command: label, status: ok ? 'pass' : 'fail', seconds: Math.round((Date.now() - started) / 1000), tail: ok ? undefined : tail });
    if (!ok) {
      add({
        severity: 'critical', rule: 'build-broken', file: `${pkg}/`, suppressible: false,
        message: `\`${label}\` fails in \`${pkg}\`${res.signal ? ` (killed: ${res.signal})` : ''}.`,
        fix: 'Fix the failure (output tail in the report), then re-run.',
      });
    }
  }
}

writeJson(path.join(args.run, 'hard.json'), { findings, warnings, commands, incomplete });
const crit = findings.filter((f) => f.severity === 'critical').length;
console.log(`hard checks: ${findings.length} findings (${crit} critical), ${warnings.length} warnings, ` +
  `commands: ${commands.map((c) => `${c.package} ${c.command} → ${c.status}`).join('; ') || 'none'}`);

function loadKnownSecrets() {
  const out = [];
  const walk = (v, name) => {
    if (typeof v === 'string' && v.length >= 16) out.push({ name, value: v });
    else if (v && typeof v === 'object') for (const [k, x] of Object.entries(v)) walk(x, name ? `${name}.${k}` : k);
  };
  const raw = readFileOrNull(path.join(homedir(), '.devdigest', 'secrets.json'));
  if (raw) {
    try {
      walk(JSON.parse(raw), 'secrets.json');
    } catch { /* unreadable secrets file: pattern checks still run */ }
  }
  for (const k of ['OPENAI_API_KEY', 'ANTHROPIC_API_KEY', 'OPENROUTER_API_KEY', 'GITHUB_TOKEN', 'GH_TOKEN']) {
    if (process.env[k] && process.env[k].length >= 16) out.push({ name: `$${k}`, value: process.env[k] });
  }
  return out;
}

/**
 * One feature per branch, any number of commits. Flags a commit whose conventional-commit
 * scope differs from the first commit's AND that touches none of the first commit's
 * packages, and branches that reference more than one course spec (L01, L02…).
 */
function featureMixWarnings() {
  const out = [];
  const commits = collect.commits;
  if (commits.length < 2) return out;
  const scopeOf = (s) => /^\w+\(([^)]+)\)!?:/.exec(s)?.[1] ?? null;
  const pkgsOf = (sha) => new Set((tryGit(['show', '--name-only', '--format=', sha], { cwd: root }) ?? '')
    .split('\n').filter(Boolean).map((p) => p.split('/')[0]));
  const [first, ...rest] = commits;
  const firstScope = scopeOf(first.subject);
  const firstPkgs = pkgsOf(first.sha);
  const odd = rest.filter((c) => {
    const s = scopeOf(c.subject);
    if (!s || !firstScope || s === firstScope) return false;
    return ![...pkgsOf(c.sha)].some((p) => firstPkgs.has(p));
  });
  if (odd.length) {
    out.push({
      rule: 'feature-mix',
      message: `Branch \`${collect.branch}\` (anchored on "${first.subject}") has commits that look like another feature: ` +
        odd.map((c) => `${c.sha.slice(0, 8)} "${c.subject}"`).join(', ') + '. Consider moving them to their own branch.',
    });
  }
  const specs = new Set(commits.flatMap((c) => c.subject.match(/\bL0\d\b/g) ?? []));
  if (specs.size > 1) {
    out.push({ rule: 'feature-mix', message: `Commits reference several course specs (${[...specs].join(', ')}) — one feature per branch.` });
  }
  return out;
}
