import type { CSSProperties } from "react";

/** Co-located styles for SkillsTab (mockup: Agent Editor · Skills). */
export const s = {
  wrap: { maxWidth: 1000, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 220,
  } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  muted: { color: "var(--text-muted)" } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 6 } satisfies CSSProperties,
  empty: {
    padding: "18px 16px",
    borderRadius: 8,
    border: "1px dashed var(--border-strong)",
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  link: { color: "var(--accent-text)" } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  row: (dragging: boolean, effective: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid " + (dragging ? "var(--accent)" : "var(--border)"),
    background: effective ? "var(--bg-elevated)" : "var(--bg-surface)",
    opacity: dragging ? 0.6 : 1,
  }),
  handle: { color: "var(--text-muted)", cursor: "grab", display: "inline-flex" } satisfies CSSProperties,
  name: { fontSize: 13, color: "var(--text-primary)" } satisfies CSSProperties,
  rowRight: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  manage: {
    fontSize: 13,
    color: "var(--accent-text)",
    marginTop: 6,
    alignSelf: "flex-start",
  } satisfies CSSProperties,
} as const;
