import type { CSSProperties } from "react";

export const s = {
  section: {
    marginBottom: 24,
  } satisfies CSSProperties,
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  fallbackReason: {
    fontSize: 12,
    color: "var(--text-muted)",
    maxWidth: 360,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  summary: {
    margin: 0,
    paddingLeft: 12,
    borderLeft: "3px solid var(--accent)",
    fontSize: 15,
    lineHeight: 1.5,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  columns: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 18,
  } satisfies CSSProperties,
  columnTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  list: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  item: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    color: "var(--text-secondary)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  itemIcon: (color: string): CSSProperties => ({ color, flexShrink: 0, marginTop: 2 }),
  notice: {
    border: "1px solid var(--warn)",
    borderRadius: 8,
    background: "var(--warn-bg)",
    padding: "10px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  noticeTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontWeight: 700,
    color: "var(--warn)",
  } satisfies CSSProperties,
  notes: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  notesTitle: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontWeight: 600,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  noticeList: {
    margin: 0,
    paddingLeft: 18,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 14,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  footerLabel: {
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginRight: 6,
  } satisfies CSSProperties,
  skeleton: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
} as const;
