import type { CSSProperties } from "react";
import { CARD_MAX_HEIGHT, CARD_WIDTH } from "./constants";

export const s = {
  trigger: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    fontSize: 13,
    fontWeight: 600,
  } satisfies CSSProperties,
  count: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    color,
  }),
  muted: { color: "var(--text-muted)" } satisfies CSSProperties,
  card: (pos: { left: number; top?: number; bottom?: number }): CSSProperties => ({
    position: "fixed",
    ...pos,
    zIndex: 50,
    width: CARD_WIDTH,
    maxHeight: CARD_MAX_HEIGHT,
    overflowY: "auto",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 10,
    boxShadow: "0 12px 32px rgba(0, 0, 0, 0.35)",
    cursor: "default",
  }),
  cardHeader: {
    position: "sticky",
    top: 0,
    padding: "10px 14px",
    background: "var(--bg-surface)",
    borderBottom: "1px solid var(--border)",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  cardBody: {
    padding: 10,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  item: (color: string): CSSProperties => ({
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    borderLeft: `3px solid ${color}`,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  }),
  itemTitleRow: { display: "flex", alignItems: "flex-start", gap: 8 } satisfies CSSProperties,
  itemTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    lineHeight: 1.35,
  } satisfies CSSProperties,
  itemMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
    fontSize: 12,
  } satisfies CSSProperties,
  itemFile: { color: "var(--text-secondary)", wordBreak: "break-all" } satisfies CSSProperties,
  itemRationale: {
    fontSize: 12,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
  cardNote: { padding: "4px 4px 6px", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
