import type { CSSProperties } from "react";

/** Co-located styles for SkillVersions. */
export const s = {
  wrap: { maxWidth: 820 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700, marginBottom: 6 } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 14 } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  item: {
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    overflow: "hidden",
  } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center" } satisfies CSSProperties,
  actions: { display: "flex", gap: 6, padding: "0 12px 0 4px" } satisfies CSSProperties,
  head: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    background: "transparent",
    border: "none",
    color: "var(--text-primary)",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    transform: open ? "rotate(90deg)" : undefined,
    transition: "transform 120ms",
  }),
  version: { fontSize: 13, fontWeight: 600 } satisfies CSSProperties,
  date: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  body: {
    margin: 0,
    padding: "12px 14px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    lineHeight: 1.5,
    whiteSpace: "pre-wrap",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  diffWrap: { borderTop: "1px solid var(--border)", background: "var(--bg-surface)" } satisfies CSSProperties,
  diffLegend: { padding: "8px 14px", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  diffSame: { padding: "0 14px 12px", fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  diff: { margin: 0, padding: "0 0 10px", fontSize: 12, lineHeight: 1.5, whiteSpace: "pre-wrap" } satisfies CSSProperties,
  diffLine: (kind: "same" | "del" | "add"): CSSProperties => ({
    padding: "0 14px",
    color: kind === "same" ? "var(--text-secondary)" : kind === "add" ? "var(--ok)" : "var(--crit)",
    background: kind === "add" ? "var(--ok-bg)" : kind === "del" ? "var(--crit-bg)" : undefined,
  }),
} as const;
