import type { CSSProperties } from "react";

/** Co-located styles for SkillStatsTab. */
export const s = {
  wrap: { maxWidth: 1100, display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  tiles: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 14,
  } satisfies CSSProperties,
  tile: {
    padding: 18,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    minHeight: 120,
    display: "flex",
    flexDirection: "column",
  } satisfies CSSProperties,
  tileHead: { display: "flex", alignItems: "center", justifyContent: "space-between" } satisfies CSSProperties,
  tileLabel: {
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tileValue: { display: "flex", alignItems: "baseline", gap: 6, marginTop: 12 } satisfies CSSProperties,
  big: { fontSize: 32, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  unit: { fontSize: 16, color: "var(--text-muted)" } satisfies CSSProperties,
  tileHint: { marginTop: "auto", paddingTop: 8, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  panels: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))",
    gap: 14,
  } satisfies CSSProperties,
  panel: {
    padding: 18,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  panelTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    marginBottom: 14,
  } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  agentList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  agentIcon: { color: "var(--accent)" } satisfies CSSProperties,
  agentName: { fontSize: 14, fontWeight: 600, flex: 1 } satisfies CSSProperties,
  open: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  footnote: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
